### PR TITLE
feat(retina): add retina support

### PR DESCRIPTION
**Pull request by michaelochs**
draw the images in the native screen scale of the main screen

note: there is no version bump in the podfile or any other maintenance stuff in this PR.

### CODE REVIEW

**Comment by timbodeit** [comment]
:+1:

**Comment by timbodeit** [comment]
@michaelochs Please have a look at this.

**Comment by timbodeit** [comment]
@michaelochs IMHO the second argument should be `NO` to allow scaling transparent images.

**Comment by michaelochs** [comment]
Yes, you are right. I corrected that. However I think sadly this project is dead.

**Comment by mustangostang** [comment]
I would not say that terms 'dead' or 'alive' are really applicable to small projects like this. Let's say it's in Schrödinger's cat state.

**Comment by michaelochs** [comment]
> I would not say that terms 'dead' or 'alive' are really applicable to small projects like this. Let's say it's in Schrödinger's cat state.

😂 nailed it! Thanks for merging! :+1:

**Pull request merged**
